version = 1

test_patterns = ["tests/"]

exclude_patterns = ["dev/"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

# [[transformers]]
# name = "autopep8"
# enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "black"
enabled = true
