exclude: >
  (?x)^(
      .+/.venv/.+|
      .+/dist/.+|
      .+/.autovenv
  )$
fail_fast: true
default_language_version:
  python: python3.8
default_stages:
  - prepare-commit-msg
  - commit
  - push
#  - post-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        stages:
          - commit
      - id: check-added-large-files
        stages:
          - commit
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: fix-encoding-pragma
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        description: Ensures that a file is either empty, or ends with one newline.
        exclude_types: [ sql ]
        # types: [text]

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args: [ --safe, --quiet ]
        language_version: python3.8
        files: \.pyi?$
        exclude: scala|doc/
        # override until resolved: https://github.com/psf/black/issues/402
        types: [ ]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: &fixtures tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [ '--config=.flake8' ]
        exclude: *fixtures
        additional_dependencies:
          - flake8-bugbear
          - flake8-coding
          - flake8-deprecated
          - flake8-isort
          - flake8-quotes
          - flake8-string-format
  #          - flake8-comprehensions
  #          - flake8-print
  #          - flake8-pep3101
  #          - flake8-isort
  #          - flake8-debugger
  #          - flake8-docstrings

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        language_version: python3.8
        args: [ "--profile", "black" ]
        files: \.py$
        exclude: scala

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.5.3
    hooks:
      - id: sqlfluff-fix
        name: sqlfluff-fix
        # Needs to use "--force" to disable confirmation
        # By default all the rules are applied
        entry: sqlfluff fix --force
        language: python
        description: 'Fixes sql lint errors with `SQLFluff`'
        types: [ sql ]
        require_serial: true
        additional_dependencies: [ ]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.5.3
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
        entry: sqlfluff lint
        language: python
        description: 'Lints sql files with `SQLFluff`'
        types: [ sql ]
        require_serial: true
        additional_dependencies: [ ]



  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.812
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: mypy
  #       language: python
  #       types: [ python ]
  #       args: [ "--ignore-missing-imports", "--scripts-are-modules" ]
  #       require_serial: true
  #       additional_dependencies: [ ]
  #       exclude: tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/|doc/|bin/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ "-ll" ]
        files: .py$

  # - repo: local
  #   hooks:
  #    - id: run pytest
  #      name: run pytest
  #      entry: poetry run pytest tests/test_pydeequ.py
  #      language: system
  #      always_run: true
  #      pass_filenames: false
