name: Greetings

on: [pull_request, issues]

jobs:
  # Send greeting
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! thanks for your contribution!, great first issue!'
        pr-message: 'Hey thanks for the input! Please give us a bit of time to review it!'
